const userConstants = {
  //------------------AUTHENTICATION--------------//
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  //------------------ACCOUNT---------------------//
  GET_INFO_SUCCESS: "GET_INFO_SUCCESS",
  GET_INFO_FAILURE: "GET_INFO_FAILURE",

  UPDATE_INFO_REQUEST: "UPDATE_INFO_REQUEST",
  UPDATE_INFO_SUCCESS: "UPDATE_INFO_SUCCESS",
  UPDATE_INFO_FAILURE: "UPDATE_INFO_FAILURE",

  //------------------VOUCHER---------------------//
  CREATE_VOUCHER: "CREATE_VOUCHER",
  DELETE_VOUCHER: "DELETE_VOUCHER",
  UPDATE_VOUCHER: "UPDATE_VOUCHER",
  GET_MY_VOUCHERS: "GET_MY_VOUCHERS",

  //------------------CAMPAIGN---------------------//
  CREATE_CAMPAIGN_REQUEST: "CREATE_CAMPAIGN_REQUEST",
  CREATE_CAMPAIGN_SUCCESS: "CREATE_CAMPAIGN_SUCCESS",
  CREATE_CAMPAIGN_FAILURE: "CREATE_CAMPAIGN_FAILURE",

  GET_MY_CAMPAIGN_REQUEST: "GET_MY_CAMPAIGN_REQUEST",
  GET_MY_CAMPAIGN_SUCCESS: "GET_MY_CAMPAIGN_SUCCESS",
  GET_MY_CAMPAIGN_FAILURE: "GET_MY_CAMPAIGN_FAILURE",

  DELETE_CAMPAIGN_REQUEST: "DELETE_CAMPAIGN_REQUEST",
  DELETE_CAMPAIGN_SUCCESS: "DELETE_CAMPAIGN_SUCCESS",
  DELETE_CAMPAIGN_FAILURE: "DELETE_CAMPAIGN_FAILURE",

  UPDATE_CAMPAIGN_REQUEST:"UPDATE_CAMPAIGN_REQUEST",
  UPDATE_CAMPAIGN_SUCCESS: "UPDATE_CAMPAIGN_SUCCESS",
  UPDATE_CAMPAIGN_FAILURE:"UPDATE_CAMPAIGN_FAILURE",

  //------------------EMPLOYEE---------------------//

  CREATE_EMPLOYEE_REQUEST: "CREATE_EMPLOYEE_REQUEST",
  CREATE_EMPLOYEE_SUCCESS: "CREATE_EMPLOYEE_SUCCESS",
  CREATE_EMPLOYEE_FAILURE: "CREATE_EMPLOYEE_FAILURE",

  GET_EMPLOYEES_REQUEST: "GET_EMPLOYEES_REQUEST",
  GET_EMPLOYEES_SUCCESS: "GET_EMPLOYEES_SUCCESS",
  GET_EMPLOYEES_FAILURE: "GET_EMPLOYEES_FAILURE",

  UPDATE_EMPLOYEE_PASSWORD_REQUEST: "UPDATE_EMPLOYEE_PASSWORD_REQUEST",
  UPDATE_EMPLOYEE_PASSWORD_SUCCESS: "UPDATE_EMPLOYEE_PASSWORD_SUCCESS",
  UPDATE_EMPLOYEE_PASSWORD_FAILURE: "UPDATE_EMPLOYEE_PASSWORD_FAILURE",

  DELETE_EMPLOYEE_REQUEST: "DELETE_EMPLOYEE_REQUEST",
  DELETE_EMPLOYEE_SUCCESS: "DELETE_EMPLOYEE_SUCCESS",
  DELETE_EMPLOYEE_FAILURE: "DELETE_EMPLOYEE_FAILURE",

  //------------------CLEAR STATE---------------------//
  REFRESH_STATE: "REFRESH_STATE",
  REFRESH_STATE_USER: "REFRESH_STATE_USER",
  REFRESH_STATE_VOUCHER: "REFRESH_STATE_VOUCHER",
  REFRESH_STATE_CAMPAIGN: "REFRESH_STATE_CAMPAIGN",
  REFRESH_STATE_EMPLOYEE: "REFRESH_STATE_EMPLOYEE",

  //------------------STATISTICAL---------------------//

  STATISTICS_VOUCHER_REQUEST: "STATISTICS_VOUCHER_REQUEST",
  STATISTICS_VOUCHER_SUCCESS: "STATISTICS_VOUCHER_SUCCESS",
  STATISTICS_VOUCHER_FAILURE: "STATISTICS_VOUCHER_FAILURE",

  LOGOUT: "LOGOUT"
};
export default userConstants;
