const userConstants = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  GET_INFO_SUCCESS: "GET_INFO_SUCCESS",
  GET_INFO_FAILURE: "GET_INFO_FAILURE",

  UPDATE_INFO_REQUEST: "UPDATE_INFO_REQUEST",
  UPDATE_INFO_SUCCESS: "UPDATE_INFO_SUCCESS",
  UPDATE_INFO_FAILURE: "UPDATE_INFO_FAILURE",

  CREATE_VOUCHER: "CREATE_VOUCHER",
  DELETE_VOUCHER: "DELETE_VOUCHER",
  UPDATE_VOUCHER: "UPDATE_VOUCHER",
  GET_MY_VOUCHERS: "GET_MY_VOUCHERS",

  CREATE_CAMPAIGN_REQUEST: "CREATE_CAMPAIGN_REQUEST",
  CREATE_CAMPAIGN_SUCCESS: "CREATE_CAMPAIGN_SUCCESS",
  CREATE_CAMPAIGN_FAILURE: "CREATE_CAMPAIGN_FAILURE",

  GET_MY_CAMPAIGN_REQUEST: "GET_MY_CAMPAIGN_REQUEST",
  GET_MY_CAMPAIGN_SUCCESS: "GET_MY_CAMPAIGN_SUCCESS",
  GET_MY_CAMPAIGN_FAILURE: "GET_MY_CAMPAIGN_FAILURE",

  REFRESH_STATE: "REFRESH_STATE",
  REFRESH_STATE_USER: "REFRESH_STATE_USER",
  REFRESH_STATE_VOUCHER: "REFRESH_STATE_VOUCHER",
  REFRESH_STATE_CAMPAIGN: "REFRESH_STATE_CAMPAIGN",

  LOGOUT: "LOGOUT"
};
export default userConstants;
